// Code generated by "go-option -type=option --trim"; DO NOT EDIT.
// Install go-option by "go get install github.com/searKing/golang/tools/go-option"

package otlpmetricgrpc

import (
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"

	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
)

// A Option sets options.
type Option interface {
	apply(*option)
}

// EmptyOption does not alter the configuration. It can be embedded
// in another structure to build custom options.
//
// This API is EXPERIMENTAL.
type EmptyOption struct{}

func (EmptyOption) apply(*option) {}

// OptionFunc wraps a function that modifies option into an
// implementation of the Option interface.
type OptionFunc func(*option)

func (f OptionFunc) apply(do *option) {
	f(do)
}

// ApplyOptions call apply() for all options one by one
func (o *option) ApplyOptions(options ...Option) *option {
	for _, opt := range options {
		if opt == nil {
			continue
		}
		opt.apply(o)
	}
	return o
}

// withOption sets option.
func withOption(v option) Option {
	return OptionFunc(func(o *option) {
		*o = v
	})
}

// WithOptionOtlpOptions appends OtlpOptions in option.
func WithOptionOtlpOptions(v ...otlpmetricgrpc.Option) Option {
	return OptionFunc(func(o *option) {
		o.OtlpOptions = append(o.OtlpOptions, v...)
	})
}

// WithOptionOtlpOptionsReplace sets OtlpOptions in option.
func WithOptionOtlpOptionsReplace(v ...otlpmetricgrpc.Option) Option {
	return OptionFunc(func(o *option) {
		o.OtlpOptions = v
	})
}

// WithOptionPeriodicReaderOptions appends PeriodicReaderOptions in option.
func WithOptionPeriodicReaderOptions(v ...sdkmetric.PeriodicReaderOption) Option {
	return OptionFunc(func(o *option) {
		o.PeriodicReaderOptions = append(o.PeriodicReaderOptions, v...)
	})
}

// WithOptionPeriodicReaderOptionsReplace sets PeriodicReaderOptions in option.
func WithOptionPeriodicReaderOptionsReplace(v ...sdkmetric.PeriodicReaderOption) Option {
	return OptionFunc(func(o *option) {
		o.PeriodicReaderOptions = v
	})
}

// WithOptionExporterWrappers appends ExporterWrappers in option.
func WithOptionExporterWrappers(v ...func(exporter sdkmetric.Exporter) sdkmetric.Exporter) Option {
	return OptionFunc(func(o *option) {
		o.ExporterWrappers = append(o.ExporterWrappers, v...)
	})
}

// WithOptionExporterWrappersReplace sets ExporterWrappers in option.
func WithOptionExporterWrappersReplace(v ...func(exporter sdkmetric.Exporter) sdkmetric.Exporter) Option {
	return OptionFunc(func(o *option) {
		o.ExporterWrappers = v
	})
}
