// Code generated by "-type Nums<int, *string> -type Nums<int, *string>"; DO NOT EDIT.
package main

import (
	"sync" // Used by sync.Map.
)

// Generate code that will fail if the constants change value.
func _() {
	// An "cannot convert Nums literal (type Nums) to type sync.Map" compiler error signifies that the base type have changed.
	// Re-run the go-syncmap command to generate them again.
	_ = (sync.Map)(Nums{})
}

var _nil_Nums_string_value = func() (val *string) { return }()

// Load returns the value stored in the map for a key, or nil if no
// value is present.
// The ok result indicates whether value was found in the map.
func (m *Nums) Load(key int) (*string, bool) {
	value, ok := (*sync.Map)(m).Load(key)
	if value == nil {
		return _nil_Nums_string_value, ok
	}
	return value.(*string), ok
}

// Store sets the value for a key.
func (m *Nums) Store(key int, value *string) {
	(*sync.Map)(m).Store(key, value)
}

// LoadOrStore returns the existing value for the key if present.
// Otherwise, it stores and returns the given value.
// The loaded result is true if the value was loaded, false if stored.
func (m *Nums) LoadOrStore(key int, value *string) (*string, bool) {
	actual, loaded := (*sync.Map)(m).LoadOrStore(key, value)
	if actual == nil {
		return _nil_Nums_string_value, loaded
	}
	return actual.(*string), loaded
}

// LoadAndDelete deletes the value for a key, returning the previous value if any.
// The loaded result reports whether the key was present.
func (m *Nums) LoadAndDelete(key int) (value *string, loaded bool) {
	actual, loaded := (*sync.Map)(m).LoadAndDelete(key)
	if actual == nil {
		return _nil_Nums_string_value, loaded
	}
	return actual.(*string), loaded
}

// Delete deletes the value for a key.
func (m *Nums) Delete(key int) {
	(*sync.Map)(m).Delete(key)
}

// Range calls f sequentially for each key and value present in the map.
// If f returns false, range stops the iteration.
//
// Range does not necessarily correspond to any consistent snapshot of the Map's
// contents: no key will be visited more than once, but if the value for any key
// is stored or deleted concurrently, Range may reflect any mapping for that key
// from any point during the Range call.
//
// Range may be O(N) with the number of elements in the map even if f returns
// false after a constant number of calls.
func (m *Nums) Range(f func(key int, value *string) bool) {
	(*sync.Map)(m).Range(func(key, value interface{}) bool {
		return f(key.(int), value.(*string))
	})
}
