// Copyright 2020 The searKing Author. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "go-option -type KetamaNodeLocator"; DO NOT EDIT.

package hashring

var _default_KetamaNodeLocator_value = func() (val KetamaNodeLocator) { return }()

// A KetamaNodeLocatorOption sets options.
type KetamaNodeLocatorOption interface {
	apply(*KetamaNodeLocator)
}

// EmptyKetamaNodeLocatorOption does not alter the configuration. It can be embedded
// in another structure to build custom options.
//
// This API is EXPERIMENTAL.
type EmptyKetamaNodeLocatorOption struct{}

func (EmptyKetamaNodeLocatorOption) apply(*KetamaNodeLocator) {}

// KetamaNodeLocatorOptionFunc wraps a function that modifies KetamaNodeLocator into an
// implementation of the KetamaNodeLocatorOption interface.
type KetamaNodeLocatorOptionFunc func(*KetamaNodeLocator)

func (f KetamaNodeLocatorOptionFunc) apply(do *KetamaNodeLocator) {
	f(do)
}

// sample code for option, default for nothing to change
func _KetamaNodeLocatorOptionWithDefault() KetamaNodeLocatorOption {
	return KetamaNodeLocatorOptionFunc(func(*KetamaNodeLocator) {
		// TODO nothing to change
	})
}

func (c *KetamaNodeLocator) ApplyOptions(options ...KetamaNodeLocatorOption) *KetamaNodeLocator {
	for _, opt := range options {
		if opt == nil {
			continue
		}
		opt.apply(c)
	}
	return c
}
