// Code generated by "go-option -type=option --trim"; DO NOT EDIT.
// Install go-option by "go get install github.com/searKing/golang/tools/go-option"

package trace

import (
	"go.opentelemetry.io/otel/attribute"

	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

// A Option sets options.
type Option interface {
	apply(*option)
}

// EmptyOption does not alter the configuration. It can be embedded
// in another structure to build custom options.
//
// This API is EXPERIMENTAL.
type EmptyOption struct{}

func (EmptyOption) apply(*option) {}

// OptionFunc wraps a function that modifies option into an
// implementation of the Option interface.
type OptionFunc func(*option)

func (f OptionFunc) apply(do *option) {
	f(do)
}

// ApplyOptions call apply() for all options one by one
func (o *option) ApplyOptions(options ...Option) *option {
	for _, opt := range options {
		if opt == nil {
			continue
		}
		opt.apply(o)
	}
	return o
}

// withOption sets option.
func withOption(v option) Option {
	return OptionFunc(func(o *option) {
		*o = v
	})
}

// WithOptionExporterEndpoints appends ExporterEndpoints in option.
// ExporterEndpoints is the target endpoint URL (scheme, host, port, path) the Exporter will connect to.
func WithOptionExporterEndpoints(v ...string) Option {
	return OptionFunc(func(o *option) {
		o.ExporterEndpoints = append(o.ExporterEndpoints, v...)
	})
}

// WithOptionExporterEndpointsReplace sets ExporterEndpoints in option.
// ExporterEndpoints is the target endpoint URL (scheme, host, port, path) the Exporter will connect to.
func WithOptionExporterEndpointsReplace(v ...string) Option {
	return OptionFunc(func(o *option) {
		o.ExporterEndpoints = v
	})
}

// WithOptionExporters appends Exporters in option.
func WithOptionExporters(v ...sdktrace.SpanExporter) Option {
	return OptionFunc(func(o *option) {
		o.Exporters = append(o.Exporters, v...)
	})
}

// WithOptionExportersReplace sets Exporters in option.
func WithOptionExportersReplace(v ...sdktrace.SpanExporter) Option {
	return OptionFunc(func(o *option) {
		o.Exporters = v
	})
}

// WithOptionResourceAttrs appends ResourceAttrs in option.
func WithOptionResourceAttrs(v ...attribute.KeyValue) Option {
	return OptionFunc(func(o *option) {
		o.ResourceAttrs = append(o.ResourceAttrs, v...)
	})
}

// WithOptionResourceAttrsReplace sets ResourceAttrs in option.
func WithOptionResourceAttrsReplace(v ...attribute.KeyValue) Option {
	return OptionFunc(func(o *option) {
		o.ResourceAttrs = v
	})
}

// WithOptionSpanAttrs appends SpanAttrs in option.
func WithOptionSpanAttrs(v ...attribute.KeyValue) Option {
	return OptionFunc(func(o *option) {
		o.SpanAttrs = append(o.SpanAttrs, v...)
	})
}

// WithOptionSpanAttrsReplace sets SpanAttrs in option.
func WithOptionSpanAttrsReplace(v ...attribute.KeyValue) Option {
	return OptionFunc(func(o *option) {
		o.SpanAttrs = v
	})
}

// WithOptionTracerProviderOptions appends TracerProviderOptions in option.
func WithOptionTracerProviderOptions(v ...sdktrace.TracerProviderOption) Option {
	return OptionFunc(func(o *option) {
		o.TracerProviderOptions = append(o.TracerProviderOptions, v...)
	})
}

// WithOptionTracerProviderOptionsReplace sets TracerProviderOptions in option.
func WithOptionTracerProviderOptionsReplace(v ...sdktrace.TracerProviderOption) Option {
	return OptionFunc(func(o *option) {
		o.TracerProviderOptions = v
	})
}
