// Code generated by "go-option -type encOpts"; DO NOT EDIT.
// Install go-option by "go get install github.com/searKing/golang/tools/go-option"

package prettyjson

// A EncOptsOption sets options.
type EncOptsOption interface {
	apply(*encOpts)
}

// EmptyEncOptsOption does not alter the configuration. It can be embedded
// in another structure to build custom options.
//
// This API is EXPERIMENTAL.
type EmptyEncOptsOption struct{}

func (EmptyEncOptsOption) apply(*encOpts) {}

// EncOptsOptionFunc wraps a function that modifies encOpts into an
// implementation of the EncOptsOption interface.
type EncOptsOptionFunc func(*encOpts)

func (f EncOptsOptionFunc) apply(do *encOpts) {
	f(do)
}

// ApplyOptions call apply() for all options one by one
func (o *encOpts) ApplyOptions(options ...EncOptsOption) *encOpts {
	for _, opt := range options {
		if opt == nil {
			continue
		}
		opt.apply(o)
	}
	return o
}

// withEncOpts sets encOpts.
func withEncOpts(v encOpts) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		*o = v
	})
}

// WithEncOptsQuoted sets quoted in encOpts.
// quoted causes primitive fields to be encoded inside JSON strings.
func WithEncOptsQuoted(v bool) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		o.quoted = v
	})
}

// WithEncOptsEscapeHTML sets escapeHTML in encOpts.
// escapeHTML causes '<', '>', and '&' to be escaped in JSON strings.
func WithEncOptsEscapeHTML(v bool) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		o.escapeHTML = v
	})
}

// WithEncOptsTruncateBytes sets truncateBytes in encOpts.
func WithEncOptsTruncateBytes(v int) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		o.truncateBytes = v
	})
}

// WithEncOptsTruncateString sets truncateString in encOpts.
func WithEncOptsTruncateString(v int) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		o.truncateString = v
	})
}

// WithEncOptsTruncateMap sets truncateMap in encOpts.
func WithEncOptsTruncateMap(v int) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		o.truncateMap = v
	})
}

// WithEncOptsTruncateSliceOrArray sets truncateSliceOrArray in encOpts.
func WithEncOptsTruncateSliceOrArray(v int) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		o.truncateSliceOrArray = v
	})
}

// WithEncOptsTruncateUrl sets truncateUrl in encOpts.
// truncate query and fragment in url
func WithEncOptsTruncateUrl(v bool) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		o.truncateUrl = v
	})
}

// WithEncOptsOmitEmpty sets omitEmpty in encOpts.
func WithEncOptsOmitEmpty(v bool) EncOptsOption {
	return EncOptsOptionFunc(func(o *encOpts) {
		o.omitEmpty = v
	})
}
