// Code generated by "go-nulljson -type=NullDuration<time.Duration>"; DO NOT EDIT.

package sql

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

func _() {
	// An "cannot convert NullDuration literal (type NullDuration) to type atomic.Value" compiler error signifies that the base type have changed.
	// Re-run the go-nulljson command to generate them again.
	_ = (sql.Scanner)(&NullDuration{})
	_ = (driver.Valuer)(&NullDuration{})
}

var _nil_NullDuration_time_Duration_value = func() (val time.Duration) { return }()

// NullDuration represents an interface that may be null.
// NullDuration implements the Scanner interface so
// it can be used as a scan destination, similar to sql.NullString.
type NullDuration struct {
	Data time.Duration

	Valid bool // Valid is true if Data is not NULL
}

// Scan implements the sql.Scanner interface.
func (nj *NullDuration) Scan(src interface{}) error {
	if src == nil {
		nj.Data, nj.Valid = _nil_NullDuration_time_Duration_value, false
		return nil
	}
	nj.Valid = true

	var err error
	switch src := src.(type) {
	case string:
		err = json.Unmarshal([]byte(src), &nj.Data)
	case []byte:
		err = json.Unmarshal(src, &nj.Data)
	case time.Time:
		srcBytes, _ := json.Marshal(src)
		err = json.Unmarshal(srcBytes, &nj.Data)
	case nil:
		nj.Data = _nil_NullDuration_time_Duration_value
		err = nil
	default:
		srcBytes, _ := json.Marshal(src)
		err = json.Unmarshal(srcBytes, &nj.Data)
	}
	if err == nil {
		return nil
	}

	return fmt.Errorf("unsupported Scan, storing driver.Value type %T into type %T : %w", src, nj.Data, err)
}

// Value implements the driver.Valuer interface.
func (nj NullDuration) Value() (driver.Value, error) {
	if !nj.Valid {
		return nil, nil
	}
	return json.Marshal(nj.Data)
}
