// Code generated by "stringer -type Event -trimprefix=Event"; DO NOT EDIT.

package httptrace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventGetConn-1]
	_ = x[EventGotConn-2]
	_ = x[EventDNSStart-4]
	_ = x[EventDNSDone-8]
	_ = x[EventConnectStart-16]
	_ = x[EventConnectDone-32]
	_ = x[EventTLSHandshakeStart-64]
	_ = x[EventTLSHandshakeDone-128]
	_ = x[EventWroteRequest-256]
	_ = x[EventGotFirstResponseByte-512]
	_ = x[EventPutIdleConn-1024]
}

const (
	_Event_name_0 = "GetConnGotConn"
	_Event_name_1 = "DNSStart"
	_Event_name_2 = "DNSDone"
	_Event_name_3 = "ConnectStart"
	_Event_name_4 = "ConnectDone"
	_Event_name_5 = "TLSHandshakeStart"
	_Event_name_6 = "TLSHandshakeDone"
	_Event_name_7 = "WroteRequest"
	_Event_name_8 = "GotFirstResponseByte"
	_Event_name_9 = "PutIdleConn"
)

var (
	_Event_index_0 = [...]uint8{0, 7, 14}
)

func (i Event) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Event_name_0[_Event_index_0[i]:_Event_index_0[i+1]]
	case i == 4:
		return _Event_name_1
	case i == 8:
		return _Event_name_2
	case i == 16:
		return _Event_name_3
	case i == 32:
		return _Event_name_4
	case i == 64:
		return _Event_name_5
	case i == 128:
		return _Event_name_6
	case i == 256:
		return _Event_name_7
	case i == 512:
		return _Event_name_8
	case i == 1024:
		return _Event_name_9
	default:
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
