// Code generated by "stringer -type TaskState -trimprefix=TaskState"; DO NOT EDIT.

package resilience

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskStateNew-0]
	_ = x[TaskStateRunning-1]
	_ = x[TaskStateDoneErrorHappened-2]
	_ = x[TaskStateDoneNormally-3]
	_ = x[TaskStateDormancy-4]
	_ = x[TaskStateDeath-5]
	_ = x[TaskStateButt-6]
}

const _TaskState_name = "NewRunningDoneErrorHappenedDoneNormallyDormancyDeathButt"

var _TaskState_index = [...]uint8{0, 3, 10, 27, 39, 47, 52, 56}

func (i TaskState) String() string {
	if i < 0 || i >= TaskState(len(_TaskState_index)-1) {
		return "TaskState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskState_name[_TaskState_index[i]:_TaskState_index[i+1]]
}
