// Code generated by "go-option -type Build"; DO NOT EDIT.

package resolver

// A BuildOption sets options.
type BuildOption interface {
	apply(*Build)
}

// EmptyBuildOption does not alter the configuration. It can be embedded
// in another structure to build custom options.
//
// This API is EXPERIMENTAL.
type EmptyBuildOption struct{}

func (EmptyBuildOption) apply(*Build) {}

// BuildOptionFunc wraps a function that modifies Build into an
// implementation of the BuildOption interface.
type BuildOptionFunc func(*Build)

func (f BuildOptionFunc) apply(do *Build) {
	f(do)
}

// sample code for option, default for nothing to change
func _BuildOptionWithDefault() BuildOption {
	return BuildOptionFunc(func(*Build) {
		// nothing to change
	})
}
func (o *Build) ApplyOptions(options ...BuildOption) *Build {
	for _, opt := range options {
		if opt == nil {
			continue
		}
		opt.apply(o)
	}
	return o
}
