// Code generated by "go-option -type ResolveNow"; DO NOT EDIT.

package resolver

// A ResolveNowOption sets options.
type ResolveNowOption interface {
	apply(*ResolveNow)
}

// EmptyResolveNowOption does not alter the configuration. It can be embedded
// in another structure to build custom options.
//
// This API is EXPERIMENTAL.
type EmptyResolveNowOption struct{}

func (EmptyResolveNowOption) apply(*ResolveNow) {}

// ResolveNowOptionFunc wraps a function that modifies ResolveNow into an
// implementation of the ResolveNowOption interface.
type ResolveNowOptionFunc func(*ResolveNow)

func (f ResolveNowOptionFunc) apply(do *ResolveNow) {
	f(do)
}

// sample code for option, default for nothing to change
func _ResolveNowOptionWithDefault() ResolveNowOption {
	return ResolveNowOptionFunc(func(*ResolveNow) {
		// nothing to change
	})
}
func (o *ResolveNow) ApplyOptions(options ...ResolveNowOption) *ResolveNow {
	for _, opt := range options {
		if opt == nil {
			continue
		}
		opt.apply(o)
	}
	return o
}
