// Code generated by "go-option -type resolveOneAddr"; DO NOT EDIT.

package resolver

// A ResolveOneAddrOption sets options.
type ResolveOneAddrOption interface {
	apply(*resolveOneAddr)
}

// EmptyResolveOneAddrOption does not alter the configuration. It can be embedded
// in another structure to build custom options.
//
// This API is EXPERIMENTAL.
type EmptyResolveOneAddrOption struct{}

func (EmptyResolveOneAddrOption) apply(*resolveOneAddr) {}

// ResolveOneAddrOptionFunc wraps a function that modifies resolveOneAddr into an
// implementation of the ResolveOneAddrOption interface.
type ResolveOneAddrOptionFunc func(*resolveOneAddr)

func (f ResolveOneAddrOptionFunc) apply(do *resolveOneAddr) {
	f(do)
}

// sample code for option, default for nothing to change
func _ResolveOneAddrOptionWithDefault() ResolveOneAddrOption {
	return ResolveOneAddrOptionFunc(func(*resolveOneAddr) {
		// nothing to change
	})
}
func (o *resolveOneAddr) ApplyOptions(options ...ResolveOneAddrOption) *resolveOneAddr {
	for _, opt := range options {
		if opt == nil {
			continue
		}
		opt.apply(o)
	}
	return o
}
