// Code generated by "go-option -type resolveNow"; DO NOT EDIT.
// Install go-option by "go get install github.com/searKing/golang/tools/go-option"

package resolver

// A ResolveNowOption sets options.
type ResolveNowOption interface {
	apply(*resolveNow)
}

// EmptyResolveNowOption does not alter the configuration. It can be embedded
// in another structure to build custom options.
//
// This API is EXPERIMENTAL.
type EmptyResolveNowOption struct{}

func (EmptyResolveNowOption) apply(*resolveNow) {}

// ResolveNowOptionFunc wraps a function that modifies resolveNow into an
// implementation of the ResolveNowOption interface.
type ResolveNowOptionFunc func(*resolveNow)

func (f ResolveNowOptionFunc) apply(do *resolveNow) {
	f(do)
}

// ApplyOptions call apply() for all options one by one
func (o *resolveNow) ApplyOptions(options ...ResolveNowOption) *resolveNow {
	for _, opt := range options {
		if opt == nil {
			continue
		}
		opt.apply(o)
	}
	return o
}

// sample code for option, default for nothing to change
func _ResolveNowOptionWithDefault() ResolveNowOption {
	return ResolveNowOptionFunc(func(*resolveNow) {
		// nothing to change
	})
}
