// Code generated by "stringer -type ConnStateHook -trimprefix=ConnStateHook"; DO NOT EDIT.

package cmux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnStateNew-0]
	_ = x[ConnStateActive-1]
	_ = x[ConnStateIdle-2]
	_ = x[ConnStateHijacked-3]
	_ = x[ConnStateClosed-4]
}

const _ConnState_name = "NewActiveIdleHijackedClosed"

var _ConnState_index = [...]uint8{0, 3, 9, 13, 21, 27}

func (i ConnState) String() string {
	if i < 0 || i >= ConnState(len(_ConnState_index)-1) {
		return "ConnStateHook(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnState_name[_ConnState_index[i]:_ConnState_index[i+1]]
}
