// Code generated by "go-import ./include"; DO NOT EDIT.

//+build

package cgo

import (
	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/architecture/x86"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/library"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/library/c"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/other"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/stacktrace"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/type_traits/detail"

	_ "github.com/searKing/golang/go/os/signal/cgo/include"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/detail"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/library/std"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/winapi"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/config"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/config/stdlib"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/container_hash"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/hardware/simd/ppc"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/hardware/simd/x86"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/hardware/simd/x86_amd"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/os"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/core"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/architecture"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/compiler"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/hardware"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/language"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/stacktrace/detail"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/config/no_tr1"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/platform"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/type_traits"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/config/abi"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/config/compiler"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/detail"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/exception"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/hardware/simd"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/config/detail"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/config/platform"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/os/bsd"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost"

	_ "github.com/searKing/golang/go/os/signal/cgo/include/boost/predef/hardware/simd/arm"
)
